### ISSUE TITLE
Portfolio should have three options

### ISSUE THREAD

**Issue by vishaalagartha** [vikasagartha/agartha-backtest#4]
Currently, we store a boolean value `True` or `False` to indicate whether the algorithm should purchase or not purchase a stock. We should migrate towards having a third option of neither purchasing nor buying.

**Comment by vikasagartha** [comment]
i think we should move toward integers ( > 0 i think).

out algorithms can be smart.

example: is this next week going to be risky? let’s drop half of our shares.

also, this allows for hold logic. if no change is required, and you own X
shares, return X.

**Comment by vishaalagartha** [comment]
Reopened issue to move towards integers
